language: ruby
sudo: false
addons:
  apt:
    packages:
    - gawk
    - wget
    - git-core
    - diffstat
    - unzip
    - texinfo
    - gcc-multilib
    - build-essential
    - chrpath
    - socat
    - libsdl1.2-dev
    - xterm
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/build/downloads
    - ${TRAVIS_BUILD_DIR}/build/sstate-cache
script:
 - . ./init-build-env
 - bitbake qt5-smart-image
